String validationEmail = r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+";
String validationName = r"^[a-z A-Z]+$";
String baseUrl = 'https://fakestoreapi.com';
String products = '/products';
String categories = '/products/categories';
String specificCategory = '/products/category/';
String arabic = 'Arabic ';
String english = 'English ';
String french = 'French ';
String ara = 'ar';
String eng = 'en';
String fre = 'fr';
